---
title: "Heart Frequency By Position"
author: "Ralph Rogge (RRO)"
date: "11/12/2016"
output:
    html_document:
        fig_width: 10
        fig_height: 6
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo=TRUE)
```

Set this flag to TRUE when you want to write out plots.
```{r}
write.plot.enabled = FALSE
```

Additional R packages
```{r, message=FALSE}
library(data.table)
library(fit)
library(ggplot2)
```

Read ANT+ FIT file
```{r}
raw <- read.fit("Raw Data/2016-11-12-11-45-20.fit")
```

Preprocess data
```{r}
data <- data.frame(heart_rate=raw$record$heart_rate) 
data$time <- cumsum(c(0,diff(raw$record$timestamp)))
data$lap <- as.numeric(cut(raw$record$timestamp, breaks=c(0,raw$lap$timestamp), labels=seq(1:10)))
data$position <- rep(NA,nrow(data))
data$position[data$lap %in% c(2,4,6)] <- "Aero"
data$position[data$lap %in% c(3,5,7)] <- "Upright"
```

```{r}
ggplot(data[data$lap > 1 & data$lap < 8,]) +
    geom_point(aes(time, heart_rate,color=position)) +
    geom_smooth(aes(time, heart_rate,color=position), method = "lm") +
    labs(title="Heart Rate by Position", x="Time [s]", y="Hear Rate [1/min]") +
    scale_colour_discrete(name="Position") +
    theme_bw()
```


